title: João Guilherme Dÿck's projects
email: joaogd53@gmail.com
description: A site I created so that I can show my projects and the cool stuff I do!
show_downloads: true
truebaseurl: "" # the subpath of your site, e.g. /blog
url: "https://jongui.github.io"
github_username:  Jongui

gem "github-pages", group: :jekyll_plugins
markdown: kramdown
theme: jekyll-theme-architect

